name: Build Unsigned iOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build web assets
        run: npm run build || echo "No build script, skipping"

      - name: Copy Capacitor assets
        run: npx cap copy ios

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios/App
          pod install
          cd ../..

      - name: Build unsigned .ipa
        run: |
          mkdir -p ios/build
          xcodebuild -workspace ios/App/App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -allowProvisioningUpdates \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     archive -archivePath ${{ github.workspace }}/ios/build/App.xcarchive
          xcodebuild -exportArchive \
                     -archivePath ${{ github.workspace }}/ios/build/App.xcarchive \
                     -exportPath ${{ github.workspace }}/ios/build \
                     -exportOptionsPlist ios/unsignedExportOptions.plist

      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-app
          path: ios/build/*.ipa
